{% set name = "txtorcon" %}
{% set version = "24.8.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/txtorcon-{{ version }}.tar.gz
  sha256: befe19138d9c8c5307b6ee6d4fe446d0c201ffd1cc404aeb265ed90309978ad0

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - automat
    - cryptography
    - python >={{ python_min }}
    - twisted >=15.5.0
    - zope.interface >=3.6.1

test:
  imports:
    - twisted.plugins
    - txtorcon
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/meejah/txtorcon
  summary: Twisted-based Tor controller client, with state-tracking and configuration abstractions.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - tdido
