{% set name = "txtorcon" %}
{% set version = "23.5.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/txtorcon-{{ version }}.tar.gz
  sha256: 93fd80a9dd505f698d0864fe93db8b6a9c1144b5feb91530820b70ed8982651c

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.8
  run:
    - automat
    - cryptography
    - incremental
    - python >=3.8
    - twisted >=15.5.0
    - zope.interface >=3.6.1

test:
  imports:
    - twisted.plugins
    - txtorcon
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/meejah/txtorcon
  summary: Twisted-based Tor controller client, with state-tracking and configuration abstractions.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - tdido
